name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./wisecow
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/wisecow-app:latest
            ${{ secrets.DOCKER_REGISTRY }}/wisecow-app:${{ github.sha }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Write kubeconfig to file
        run: echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
        run: |
          kubectl set image deployment/wisecow wisecow=${{ secrets.DOCKER_REGISTRY }}/wisecow-app:${{ github.sha }} -n default 